config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :categories
  root "articles#index"
 
  resources :articles do
    resources :comments
  end
  
  get '/search',to: "articles#search"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  belongs_to :category
  has_many :comments, dependent: :destroy
  has_one_attached :image, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
  validates :commenter, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

       def configure_permitted_parameters
            #devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
            #devise_parameter_sanitizer.permit(:account_update, keys: [:name])
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
       end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  
  def index
    @articles = Article.order("id DESC").page(params[:page]).per(5)
  end

  def show
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
    
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path, status: :see_other
  end

  def search
    if params[:search].blank?
      redirect_to root_path and return
    else
      @parameter = params[:search].downcase
      @results = Article.where("title LIKE :search", search: "%#{@parameter}%")
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :image, :status, :category_id)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: :see_other
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/controllers/users/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.slim
= form_with model: article do |form|
  div.form-group
    = form.label :title
    br
    = form.text_field :title, class: "form-control"
    - article.errors.full_messages_for(:title).each do |message|
      div= message

  div.form-group
    = form.label :body
    br
    = form.text_area :body , class: "form-control"
    br
    - article.errors.full_messages_for(:body).each do |message|
      div= message

  div.form-group
    = form.label :Image
    = form.file_field :image

  div
    = form.label :status
    br
    = form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public'

  div.form-group.mt-3
    = form.label :category
    br
    = form.select :category_id, options_for_select(Category.all.map { |category| [category.name, category.id]})

  div.mt-5
    = form.submit class:"btn btn-primary"


app/views/articles/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  = link_to "Articles", root_path, class: "navbar-brand"
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon

  div.collapse.navbar-collapse#navbarNav
    ul.navbar-nav.mr-auto
      li.nav-item
        = link_to "Categories", categories_path, class: "nav-link"

      - if user_signed_in?
        li.nav-item
          = link_to "Add Category", new_category_path, class: "nav-link"

        li.nav-item
          = link_to "Add Article", new_article_path, class: "nav-link"

        li.nav-item
          = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link"

        li.nav-item
          = link_to "Edit Profile", edit_user_registration_path, class: "nav-link"
      - else
        li.nav-item
          = link_to "Sign In", new_user_session_path, class: "nav-link"

        li.nav-item
          = link_to "Sign Up", new_user_registration_path, class: "nav-link"

    = form_tag(search_path, method: "get")
      div.input-group
        = search_field_tag :search, params[:search], placeholder: "Type", class: "form-control"
        div.input-group-btn.ml-3
          = button_tag "Search", class: "btn btn-primary", name: nil

app/views/articles/edit.html.slim
h1 Edit Article
= render "form", article: @article

app/views/articles/index.html.slim
div.card.mt-3
  div.card-header
    h1 Articles

  div.card-body
    |Our blog has #{Article.public_count} articles and counting!

    div.list-group.mt-3
      - @articles.each do |article|
        button.list-group-item.list-group-item-action  type="button" 
          - unless article.archived?
            = link_to article.title, article
      br
      div.container.page-pagination
        = paginate @articles

    div.mt-3
      = link_to 'New Article', new_article_path, class: "btn btn-primary"

app/views/articles/new.html.slim
div.card.mt-3
  div.card-header
    h1 New Article

  div.card-body
    = render "form", article: @article

app/views/articles/search.html.slim
h2.mt-5 Search Results

div.list-group.mt-5
  - @results.each do |result|
    button.list-group-item.list-group-item-action type="button" 
      = link_to result.title,result

app/views/articles/show.html.slim
div.mt-5
  - if @article.image.attached?
    img src=url_for(@article.image) style="width: 100%; height: 300px;"

div
  .jumbotron.jumbotron-fluid
    .container
      h1.display-4
        h1= @article.title
      p.lead
        p= @article.body

div
  = link_to "Edit", edit_article_path(@article), class: "btn btn-primary"
  = link_to "Delete", article_path(@article), class: "btn btn-danger ml-2", 
  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }

h2.mt-5 Comments
= render @article.comments

div.card.mt-3.container
  div.card-header
    h2 Add a comment:
  div.card-body
    = render 'comments/form'

app/views/categories/_category.html.slim
h3 #{category.name}

app/views/categories/_form.html.slim
= form_with(model: category) do |form|
  - if category.errors.any?
    div style="color: red"
      h2 = pluralize(category.errors.count, "error")
      | prohibited this category from being saved:

      ul
        - category.errors.each do |error|
          li = error.full_message

  div.form-group
    = form.label :name
    = form.text_field :name , class: "form-control"

  div
    = form.submit class: "btn btn-primary"

app/views/categories/edit.html.slim
h1.mt-5 Editing category

= render "form", category: @category
br
div
  = link_to "Show this category", @category ,class: "btn btn-primary"
  = link_to "Back to categories", categories_path , class: "ml-2 btn btn-primary"

app/views/categories/index.html.slim
div.card.mt-3
  div.card-header
    h1 Categories

  div.card-body
    div.list-group.mt-4
      - @categories.each do |category|
          button.list-group-item.list-group-item-action type="button"
            div.d-flex.justify-content-between.align-items-center
              h5.mb-3
                = link_to category.name,category
              = link_to "Show this category", category , class: "btn btn-primary"
        
    = link_to "New category", new_category_path , class: "btn btn-primary mt-3"
  

app/views/categories/new.html.slim
div.card.mt-3
  div.card-header
    h1 New category

  div.card-body
    = render "form", category: @category
    div.mt-3
      = link_to "Back to categories", categories_path , class: "btn btn-primary"

app/views/categories/show.html.slim
.card.mt-3
  .card-header
    h3 = render @category

  .card-body
    .list-group
      - @category.articles.each do |article|
        button.list-group-item.list-group-item-action
          = link_to article.title, article

    div
      = link_to "Edit this category", edit_category_path(@category), class: "mt-3 btn btn-primary"
      = link_to "Back to categories", categories_path, class: "mt-3 btn btn-primary ml-3"
      = button_to "Destroy this category", @category, class: "mt-3 btn btn-danger",
      data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }

app/views/comments/_comment.html.slim
- unless comment.archived?
  div.row.d-flex
    div.col-md-8.col-lg-6
      div.card.mb-4
        div.card-body
          p = comment.body
          div.d-flex.justify-content-between
            p.small.mb-0.ms-2 = comment.commenter          
            p
              = link_to "Destroy Comment", [comment.article, comment], 
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  

app/views/comments/_form.html.slim
= form_with model: [ @article, @article.comments.build ] do |form|
  div.form-group
    = form.label :commenter
    br
    = form.text_field :commenter, class: "form-control"

  div.form-group
    = form.label :body
    br
    = form.text_area :body , class: "form-control"

  p
    = form.label :status
    br
    = form.select :status, Visible::VALID_STATUSES, selected: 'public'

  p
    = form.submit class:"btn btn-primary"

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous"

    title Article App

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  body
    = render 'articles/header'
    div.container
      - if notice
        p.alert.alert-success.mt-3= notice
      - if alert
        p.alert.alert-danger.mt-3= alert
      == yield

    script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"